# Generated by Django 3.2.4 on 2021-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='air_conditioning',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='attic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='basement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='building_area_sq_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='building_condition_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='building_quality_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='construction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='exterior_walls',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='fireplace',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='full_bath_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='garage_parking_of_cars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='garage_type_parking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='heating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='heating_fuel_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='no_of_buildings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='no_of_stories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='number_of_bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='number_of_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='partial_bath_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='pool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='property_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='roof_cover',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='roof_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='sewer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='site_area_acres',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='subdivision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='total_bath_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='total_number_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='water',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='zoning',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
